apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
      service: apps-service #Name of service
  name: deployment-apps
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: herreraluis/javademo
          ports:
            - containerPort:  8080
              hostPort: 8080

          command: ["java"]
          args: ["-Dspring.profiles.active=$PROFILE", "-Dpassword_db=$PASSWORD_DB", "-Dusername_db=$USERNAME_DB", "-Durl_db=$URL_DB", "-jar", "app.jar"]
