FROM maven:3.3-jdk-8-alpine
WORKDIR /opt
COPY pom.xml ./
COPY scripts/start_app.sh ./
COPY ./src ./src
RUN mvn -B -f ./pom.xml -s /usr/share/maven/ref/settings-docker.xml -Dmaven.test.skip=true install