FROM maven:3.3-jdk-8
COPY pom.xml /opt/
COPY scripts/start_app.sh /opt/
COPY ./src /opt/src
WORKDIR /opt
RUN mvn -B -f /opt/pom.xml -s /usr/share/maven/ref/settings-docker.xml -Dmaven.test.skip=true install