apiVersion: v1
kind: Service
metadata:
  name: service-apps
  labels:
    app: webapp
    role: master
    tier: backend
spec:
  selector:
   app: deployment-apps
  ports:
   -  name: tcp-5432
      protocol: TCP
      port: 5432
      targetPort: 5432

   -  name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080