spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo
    password: supersecret
    platform: postgres
    driver-class-name: org.postgresql.Driver