spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/datadb
    username: demo
    password: the-secret
    platform: postgres
    driver-class-name: org.postgresql.Driver
---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://^param.url_db^
    username: ^param.username^
    password: ^param.password^
    platform: postgres
    driver-class-name: org.postgresql.Driver