pipeline {
    agent none
    options {
        skipDefaultCheckout(true)
    }
    stages {
                stage('Checkout code') {
                        steps {
                            node('docker') 
                                {
                                    checkout([
                                            $class                           : 'GitSCM',
                                            branches                         : [[name: '*/master']],
                                            doGenerateSubmoduleConfigurations: false,
                                            extensions: [[$class: 'CloneOption', timeout: 19]],
                                            submoduleCfg                     : [],
                                            userRemoteConfigs                : [[url: 'https://github.com/herrera-luis/example-springboot']]]
                                    )
                                }
                            }
                        }
                stage('Build artifacts') {
                        steps {
                            echo 'building artifacts..'
                            node('docker') {
                                sh '''
                                    sh ./scripts/local_build_artifact.sh --clean
                                    '''
                            }
                        }
                    }
                stage('Deploy app') {
                        steps {
                            echo 'deploy app..'
                            node('docker') {
                                sh '''
                                    sh ./scripts/local_deploy.sh
                                    '''
                            }
                        }
                    }
            }
}
 